### ISSUE TITLE
remove dependency to concrete logger from TMD ?

### ISSUE THREAD

**Issue by behrica** [techascent/tech.ml.dataset#164]
See here:
https://github.com/zero-one-group/geni/pull/287#discussion_r518957733

**Comment by cnuernber** [comment]
Answered there.  Although that is about this toolkit we should keep the thread open there as someone there may know a ton about Java logging that I do not.  Thanks for the heads up and I do see your point.

**Comment by behrica** [comment]
I think I found a better way.
It removes logging dependencies from TMD, so somebody using TMD does not pull in any logger dependency.
This is the right behavior for a library, in my view.

This means, in the repl we have no logging at all.

Adding logging to the repl gets done by specifying a `logback` dependendency in leiningen profile "repl".
This will then activate the default behaviour of logback, which is to create a basic logger with level Debug.

This makes a lot of noise, but can be changed in the repl by:

```clojure
(import '[ch.qos.logback.classic Level])
(import '[ch.qos.logback.classic Logger])
 (.setLevel  (org.slf4j.LoggerFactory/getLogger (Logger/ROOT_LOGGER_NAME)) Level/WARN)
```

This can be added to the ":init" of repl options, so executes on repl start.

**Comment by behrica** [comment]
This seems to work fine, all test pass.

I can do a PR.

**Comment by cnuernber** [comment]
I need to see how this affects very new people first.  Especially people coming from a deps pathway; they may not know how to do what you are doing.  Please read my comment in the other thread.

**Comment by behrica** [comment]
Maybe it can be solved by documenting clearly how to use TDM as a "tool"   (vs use as a library):

The logging problem could be solved with an other "wrapper" artifact, so you would call "TDM as a tool" this way:
```
clj -Sdeps '{:deps {techascent/tech.ml.dataset.repl {:mvn/version "5.00-alpha-21"}}}' 
```

which would add the needed logging deps + setup of the logging eventually (or provides a simple helper function to do so).
This is half way into making a proper cli tool. (like geni did)

In this way we could even add the "provided" dependencies, and have a more complete beginner experience.

**Comment by cnuernber** [comment]
Do you realize that the spark system also includes its logging system?  And that that, along with slf4j's half-baked design is the issue here?  dtype-next doesn't have this issue, it comes with using Smile which brings in slf4j.  

I think this is more of a religious issue than a concrete one.  The work around is simple and the way the system is works for strictly more new people than anything else proposed.  Advanced people can configure logging with a bit more nuance.  I don't find the current argument which seems to boil down into 'I don't think it should work this way' very convincing as compared to this library working correct even a couple times for brand new people.  

A wrapper library or a repl-specific library is something you are welcome to maintain yourself and it could exclude dependencies and thus the burden of updating multiple libraries, of which I do already, is shared at least somewhat by the people who care about the issue.

**Comment by cnuernber** [comment]
Furthermore putting the default logging in your global config means you risk dependency issues with every single project you work on.  That seems to me to be the worst possible solution.
