### ISSUE TITLE
dataset key-fn option unexpected behavior

### ISSUE THREAD

**Issue by chamaeleon** [techascent/tech.ml.dataset#259]
When providing a key-fn option to transform the header for columns, it is processed multiple times, resulting in a somewhat unexpected behavior.
```clojure
(-> [{"Foo" 1 , "Bar" 2}] (tech.v3.dataset/->dataset {:key-fn #(do (println (type %) %) (keyword (.toLowerCase %)))}))
java.lang.String Foo
java.lang.String Foo
java.lang.String Bar
java.lang.String Bar
clojure.lang.Keyword :bar
; Execution error (IllegalArgumentException) at titanic.core/eval28780$fn (form-init2972723852524916178.clj:1).
; No matching field found: toLowerCase for class clojure.lang.Keyword
(-> [{"Foo" 1 , "Bar" 2}] (tech.v3.dataset/->dataset {:key-fn #(do (println (type %) %) (keyword (.toLowerCase (name %))))}))
java.lang.String Foo
java.lang.String Foo
java.lang.String Bar
java.lang.String Bar
clojure.lang.Keyword :bar
clojure.lang.Keyword :foo
_unnamed [1 2]:

| :bar | :foo |
|-----:|-----:|
|    2 |    1 |
```
Due to the iterative process seemingly taking place within the dataset generation, the third time around it appears the result of a previous application of the key-fn is used, which means it is already a keyword, and one can't get the lowercase version of a string, which is on the surface what one expect the input to the function to be (or at least I feel this would be the case).

**Comment by cnuernber** [comment]
This is a totally legitimate issue because the column names are used to define the column parsers *and* the ->dataset function, which is used after the columns have been parsed, has a key-fn optional argument.  Thus key-fn can be called twice and thus currently has to be idempotent `(= (f(f x)) (f x))`  Type transformations such as `string->keyword` tend to fulfill this requirement but it is perhaps too strong of a requirement or needs to be better documented.

**Comment by chamaeleon** [comment]
Personally, clarified documentation would be sufficient if it is more desirable to keep the idempotent characteristic. Given the current requirement, it could of course fail in a non-error way (and I realize my example is contrived and the replacement should be more precise) when naively trying to remove "ABC_" from the key, but without knowing what the behavior is (through documentation), I would first try to figure out what my trim-prefix function is doing wrong (who among us can say they have never constructed a regex incorrectly...)
```
(defn trim-prefix [s]
  (str/replace s #"^[^_]*_" ""))

(-> [{"ABC_Type" 1 , "ABC_Currency_Value" 2}] (tech.v3.dataset/->dataset {:key-fn trim-prefix}))
_unnamed [1 2]:

| Type | Value |
|-----:|------:|
|    1 |     2 |
```

**Comment by cnuernber** [comment]
Yep, agree 100% and people will want to do this.  In this case it would be possible to work around this by just not using key-fn at all and post-processing the dataset after load but it would be best if key-fn were fixed.

**Comment by chamaeleon** [comment]
I have no particular problem with using a function like the one below for the original problem (it rubs me the wrong way doing the `name->lowercase->keyword` thing on a keyword like I worked around it in the first post). And I suspect 98% (sample size unknown, do not trust result) of the use cases by people so far is to just use the `keyword` function in isolation.
```
(defn my-key-fn [k]
  (if (= (type k) java.lang.String)
    (keyword (.toLowerCase k))
    k))
```

**Comment by joinr** [comment]
@cnuernber daniel just ran into this again https://clojurians.zulipchat.com/#narrow/stream/236259-tech.2Eml.2Edataset.2Edev/topic/strange.20behaviour.20trying.20to.20name.20columns.20with.20key-fn.  I think the idempotency requirement is not necessary.  At least, tracing through the causal chain for his specific example, it seems that you could elide the key-fn check after parsing, since the column parsing phase already does everything.

So in  https://github.com/techascent/tech.ml.dataset/blob/master/src/tech/v3/dataset/io/context.clj#L105

change the new-dataset call to just not use a key-fn:

(defn parsers->dataset
  ([options parsers row-count]
   (let [parsers (if (instance? Map parsers)
                   (vals parsers)
                   parsers)
         all-parsers (->> parsers
                          (remove nil?))
         row-count (long row-count)]
     (->> all-parsers
          (mapv (fn [{:keys [column-name column-parser]}]
                  (assoc (column-parsers/finalize! column-parser row-count)
                         :tech.v3.dataset/name column-name)))
          (ds-impl/new-dataset (assoc options :key-fn identity))))
  ([options parsers]
   (parsers->dataset options parsers
                     (apply max 0 (map (comp dtype/ecount :column-parser)
                                       parsers)))))

I "think" that works within the existing pipeline (for the mapseq path) and follows the prinicple of least surprise for the user.  Uncertain if this affects other paths.

**Comment by joinr** [comment]
It does put responsibility on the caller to ensure that their parser targets for column names line up with the possible universe of outputs from their key-fn though.
