### ISSUE TITLE
Thoughts on the current java demo

### ISSUE THREAD

**Issue by harold** [techascent/tech.ml.dataset#285]
Rad! This is so thought provoking. I've never seen anything like this.

There's a lot here. I could imagine an even smaller/simpler one that does less for the **very first** introduction. This demo is super-valuable though.

---

https://github.com/techascent/tech.ml.dataset/blob/15cd6b6bed415bbd9228d42f956c64847f9552e6/java_test/java/jtest/TMDDemo.java#L77

I'm no Java expert, but is it possible and worth it to have the thing returned by `.get` work with `[]` indexing?

Something like `ds.get("price")[0]` may be more java-y instead of `call(priceCol, 0)`.

*Of course, `call` is mind-boggling, but maybe too much of a clojure-ism*

---

https://github.com/techascent/tech.ml.dataset/blob/15cd6b6bed415bbd9228d42f956c64847f9552e6/java_test/java/jtest/TMDDemo.java#L80-L82

Right here I'm not sure if the `kw` is getting you much. Can the column names be strings? Maybe that's ok in Java?

---

https://github.com/techascent/tech.ml.dataset/blob/15cd6b6bed415bbd9228d42f956c64847f9552e6/java_test/java/jtest/TMDDemo.java#L103-L108

This may read better as multiple lines. I am surprised by how terse the `LongReader` implementation can be.

Also, is `head` necessary here? Does printing the whole ds do something ugly?

---

https://github.com/techascent/tech.ml.dataset/blob/15cd6b6bed415bbd9228d42f956c64847f9552e6/java_test/java/jtest/TMDDemo.java#L123-L129

Similar here w/ the `[]` indexing...

---

https://github.com/techascent/tech.ml.dataset/blob/15cd6b6bed415bbd9228d42f956c64847f9552e6/java_test/java/jtest/TMDDemo.java#L154

Just noticed `Map stocks = ...` here. Is `Map` preferable to `var`?

---

https://github.com/techascent/tech.ml.dataset/blob/15cd6b6bed415bbd9228d42f956c64847f9552e6/java_test/java/jtest/TMDDemo.java#L159

This is just not bad for java, imo. Nice.

---

https://github.com/techascent/tech.ml.dataset/blob/15cd6b6bed415bbd9228d42f956c64847f9552e6/java_test/java/jtest/TMDDemo.java#L180-L185

This is sweet, java verging on elite. There may be a slicker way to express it:
 - https://docs.oracle.com/javase/tutorial/java/javaOO/lambdaexpressions.html#syntax

Again, I'm no expert.

---

https://github.com/techascent/tech.ml.dataset/blob/15cd6b6bed415bbd9228d42f956c64847f9552e6/java_test/java/jtest/TMDDemo.java#L212-L229

This is super interesting. There is potential for confusion w/ mutability for pandas victims and other java folks. Personally, I'm not even sure. Is `stocks` mutated after this bit? Looks like maybe 'no' ? ...

---

https://github.com/techascent/tech.ml.dataset/blob/15cd6b6bed415bbd9228d42f956c64847f9552e6/java_test/java/jtest/TMDDemo.java#L242-L247

From a finance-as-a-domain perspective, this would be much more interesting grouped by ticker symbol, or perhaps on a filtered dataset of only a single ticker. min/mean/max across names is odd.

---

https://github.com/techascent/tech.ml.dataset/blob/15cd6b6bed415bbd9228d42f956c64847f9552e6/java_test/java/jtest/TMDDemo.java#L263

Gasping-face emoji.

`var` here, maybe, instead of `Object`... or?

---

https://github.com/techascent/tech.ml.dataset/blob/15cd6b6bed415bbd9228d42f956c64847f9552e6/java_test/java/jtest/TMDDemo.java#L316

This is cool, but I think joining on a single column is a much more common case and may serve as a better first example.

---

https://github.com/techascent/tech.ml.dataset/blob/15cd6b6bed415bbd9228d42f956c64847f9552e6/java_test/java/jtest/TMDDemo.java#L422

This is wild. Maybe worth considering making the underlying function work with strings as well as keywords to avoid `kw` at the call site here.

**Comment by cnuernber** [comment]
Thanks for the careful feedback!

Let's get to the things I am going to push back on first - 

* `[]` - as far as I know you cannot overload the square bracket operator in java.  Note that java.util.List doesn't do anything like this but provides a .get function.  Perhaps Kotlin or Scala can make these things look more similar but raw java doesn't have *any form of operator overloading* - hence the `call` operator in the Clj namespace :-).
* `var` - Only java 10+.  I think it would make the demo a bit more concise and were we doing a project I would use it liberally but one thing to be clear is that this system currently supports JDK-8.
* `lambda` - Lambda expressions only work on what the Java spec defines as `functional` interfaces - an interface with only 1 method defined.  Note their incorrect use of `functional` which matches their incorrect use of `heap` in the term `off-heap` - somehow a partial understanding of language concepts is acceptable on the Java standards committee.  What is possible is for functions like `filter` I could expose a derived interface that uses java.util.function.Function which the compiler would auto-detect but I am not sure if the compiler could pickup the correct overload so that may remove the ability to use an `IFn` and for operators like `map` which rely on multiple-arity IFn functionality it can't work.  Well, I mean, we can map every function to java.util.functional.Function by making a vector of the args.  For very concise code this may be worth it.
* Allow some subset of functions to use strings instead of keywords - This feels like a lot of work.  Literally every function takes an option map and that option map would need special processing across the board.  There is a special function exposed to java from DType called `opts` which will automatically ensure the keys are keywords but I have avoided it here for clarity.  For the first cut I don't want to change/retest large portions of the dataset implementation.
* I could also imagine demos that do less for sure.  Perhaps the community will come through and produce a few of those.  If I were a java programmer then for me at least it is useful to scan the entire file to see the extent of the provided functionality then I can zero in on exactly what my task is.  The other option is to create many small .java demos but that is considerably more work for me.  Perhaps there can be a `recipe's` section of the wiki - something Clojure people also very much appreciate.

Now onto the things I can do something about:

1. Don't use keywords where strings will do - done.
2. Don't use `head` for short datasets - done.
3. Be clear about immutability - To be very clear, no datasets were mutated in the demo.  I will say something about this to help heal the pandas-damaged-brains.  Local variables were reassigned to different datasets but all datasets were changed as if they were immutable and the API doesn't expose the inner mutation pathways. 
4. The financial stuff now just uses GOOG.
5. Added a quick file length comparison at the end for serialized formats.

Leaving open as I think perhaps we can think more about the things I didn't do on this pass.

**Comment by harold** [comment]
That's awesome. Great work!

**Comment by cnuernber** [comment]
Closing for now.

I think there are at least three interesting points raised overall by this pathway.

1.  Java lacks a generic call mechanism.  If java had an IFn equivalent that Clojure worked with and that the compile auto-casted an expression like `data(a,b,c)` to be an instance of that iface then that would really help inter-language interoperability.  The most minimal expression of interoperability to me is the call operator - it seems rather fundamental.
2. Java lacks a generic indexing mechanism like you note above.  That makes numeric code in Java look considerably worse or you have to use arrays of arrays which are specifically a bad abstraction for ND data.  A generic mechanism that allowed read/write with long addressing in object, double, long spaces that was compiler supported in some basic ways would go a long way especially if hotspot had an understanding of this along with some of the addressing mechanisms.  That should allow for significantly more optimization when using fixed datatypes in various nested looping constructs.
3. Lambdas could be a lot better.  Specifically it would make sense to be able to implement interfaces with multiple member functions with a shorthand syntax.

**Comment by harold** [comment]
Interesting how this raises ideas around Java the language.

I didn't realize that Java 8 was an option, esp. for `import static` - that's cool that it goes back that far, and people on more recent Javas that support `var` will def use.

Very cool.
