### ISSUE TITLE
Creating own aggregation function

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.ml.dataset#42]
What is the best way if I want to create my own aggregate function?
I know that I can always `reduce` on columns but then I escape from `datatype` flow.

**Comment by cnuernber** [comment]
There are a few options.  Reduce is pretty fast honestly as it switches to an iterator style if the item is iterable so calling `(->> (dtype/->reader col) (reduce ...)` will be about as fast as you can get for untyped reduction.  I tried to beat Clojure's reduce for the generic case and could only match it, props to Alex and crew!

Moving into typed math, there are two types of reductions.  If you know your operator is commutative, there is a parallelized reduction operator.  Here are some timings:
```clojure

user> (require '[tech.v2.datatype.binary-op :as binary-op])
nil
user> (require '[tech.v2.datatype.reduce-op :as reduce-op])
nil
user> (require '[criterium.core :as crit])
nil
user> (def double-data (double-array (range 100000)))
#'user/double-data
user> (set! *unchecked-math* false)
false
user> (crit/quick-bench (reduce  #(+ %1 %2) double-data))
Evaluation count : 96 in 6 samples of 16 calls.
             Execution time mean : 6.298241 ms
    Execution time std-deviation : 112.680710 µs
   Execution time lower quantile : 6.151980 ms ( 2.5%)
   Execution time upper quantile : 6.459879 ms (97.5%)
                   Overhead used : 9.218808 ns

Found 1 outliers in 6 samples (16.6667 %)
	low-severe	 1 (16.6667 %)
 Variance from outliers : 13.8889 % Variance is moderately inflated by outliers
nil
user> (crit/quick-bench (reduce  #(unchecked-add (double %1) (double %2)) double-data))
Evaluation count : 120 in 6 samples of 20 calls.
             Execution time mean : 5.229000 ms
    Execution time std-deviation : 125.310697 µs
   Execution time lower quantile : 5.103052 ms ( 2.5%)
   Execution time upper quantile : 5.413921 ms (97.5%)
                   Overhead used : 9.218808 ns
nil
user> (crit/quick-bench (reduce-op/commutative-reader-reduce {}  #(unchecked-add (double %1) (double %2)) double-data))
Evaluation count : 492 in 6 samples of 82 calls.
             Execution time mean : 1.233972 ms
    Execution time std-deviation : 12.445114 µs
   Execution time lower quantile : 1.211857 ms ( 2.5%)
   Execution time upper quantile : 1.244495 ms (97.5%)
                   Overhead used : 9.218808 ns

Found 1 outliers in 6 samples (16.6667 %)
	low-severe	 1 (16.6667 %)
 Variance from outliers : 13.8889 % Variance is moderately inflated by outliers
nil
user> (def binary-plus (binary-op/make-binary-op :float64 (unchecked-add x y)))
#'user/binary-plus
user> (crit/quick-bench (reduce-op/commutative-reader-reduce {} binary-plus double-data))
Evaluation count : 1152 in 6 samples of 192 calls.
             Execution time mean : 526.025514 µs
    Execution time std-deviation : 7.931317 µs
   Execution time lower quantile : 518.546745 µs ( 2.5%)
   Execution time upper quantile : 536.691958 µs (97.5%)
                   Overhead used : 9.218808 ns
nil
```

So, depending how how important that reduction really is and if it is a commutative operation or not, you can get quite a lot faster using typed operators.

Somehow `dfn/reduce-+` is twice as fast yet of the fastest but I think this is potentially because it is hitting some hotspot fastpath; I can't tell.

If your operation isn't commutative then I really do think `clojure.core/reduce` is darn near as fast as you can get.  If it is, there is a big win from parallelizing it, and a relatively small win from making it strongly typed.

All else fails, breaking out `tech.parallel.for/indexed-map-reduce` for that exact operation is by far the most general way to do a fast, parallelized reduction (or mapping) so that is the final escape hatch if you think parallelization will help.

**Comment by cnuernber** [comment]
Final timings if you want to hardcode everything:
```clojure

user> (require '[tech.parallel.for :as parallel-for])
nil
user> (crit/quick-bench 
       (parallel-for/indexed-map-reduce
        100000
        (fn [^long start-idx ^long len]
          (let [end-idx (+ start-idx len)]
            (loop [accum 0.0
                   idx start-idx]
              (if (< idx end-idx)
                (recur (unchecked-inc idx)
                       (unchecked-add accum (aget ^doubles double-data idx)))
                accum))))
        ;;Final summation of remaining members
        (partial reduce +)))
Evaluation count : 31590 in 6 samples of 5265 calls.
             Execution time mean : 18.837752 µs
    Execution time std-deviation : 503.879330 ns
   Execution time lower quantile : 18.203412 µs ( 2.5%)
   Execution time upper quantile : 19.449245 µs (97.5%)
                   Overhead used : 9.218808 ns
nil
```

**Comment by cnuernber** [comment]
So we started at 6ms and went down to 19us.  It all depends on how much work you want to do and how important the operation really is.

**Comment by genmeblog** [comment]
Great, thanks for thorough explanation. I've seen already using `indexed-map-reduce` somewhere. That's really cool and is indeed fast as hell.

**Comment by cnuernber** [comment]
Its is a cool primitive, like the implementation of [arggroup-by](https://github.com/techascent/tech.datatype/blob/master/src/tech/v2/datatype/builtin_op_providers.clj#L356).  

It maps to an out-of-core reduction of the entire dataset to something that will fit in-core and an in-core finalization pathway to a result.  I can't think of anything faster for a generalized parallelization primitive.

**Comment by cnuernber** [comment]
And then the TVM reduction operator as a final reference:
https://docs.tvm.ai/tutorials/language/reduction.html

**Comment by cnuernber** [comment]
Closing this for now.  Not sure if any further information would be helpful.
