### ISSUE TITLE
group-by and aggregate

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.ml.dataset#43]
Aggregation on dataset and on groups (after group-by) should result a dataset. As @keesterbrugge shows it can be done with some Clojure operations. Wonder if there are more optimal versions.

```clojure
(defn aggregate
  ([agg-fns-map ds]
   (aggregate {} agg-fns-map ds))
  ([m agg-fns-map ds]
   (into m (map (fn [[k agg-fn]]
                  [k (agg-fn ds)]) agg-fns-map))))

(def aggregate->dataset (comp ds/->dataset vector aggregate))

(defn group-by-columns-and-aggregate
  [gr-colls agg-fns-map ds]
  (->> (ds/group-by identity ds gr-colls)
       (map (fn [[group-idx group-ds]]
              (aggregate group-idx agg-fns-map group-ds)))
       ds/->dataset))
```

Results can be found here: https://github.com/genmeblog/techtest/blob/master/src/techtest/core.clj#L642

**Comment by genmeblog** [comment]
I think that single `group-by` without aggregation should stay the same, ie. map of datasets. Possibly `ungroup` function could be introduced.

**Comment by cnuernber** [comment]
I have a bad version of this:

https://github.com/techascent/tech.ml.dataset/blob/master/src/tech/ml/dataset/base.clj#L634

The problems I ran across is the aggregation is dependent upon column datatype and what is the actual signature of the aggregation fn.  

This could I think be split up into two parts: group-by and a sort of columnwise reduction where your reduce operator takes a column and returns a scalar.  This then returns a new dataset.

**Comment by genmeblog** [comment]
How to run this function? Simple `(ds/aggregate-by-column :V1 DS {:count-column-name "n"})` throws exception.

**Comment by cnuernber** [comment]
This is what Sami said too.  I would recommend we step away from that and start from some first principles.  

What do you think about a dataset `reduce` primitive.

**Comment by genmeblog** [comment]
`reduce` primitive sounds good. Question if it cover all the cases.

First I would leave group-by part now (which is essencially collection of datasets to be combine after aggregation). So we have aggregation, which can:

1. Convert column into value (mean, max, min, count, ...)
2. Convert columns into value (sum, dot, max of sum, ...)
3. Convert column or columns into values (confidence-interval, ...)
All cases produce flat row which is then returned as dataset.

So aggregation function is a function which gets column(s) and returns value(s). We want to assign names to the result.

Regarding grouping: I think that every function which accept dataset should work on grouped dataset too.  In such case function is applied to every group separately (parallely) and then is combined back to a single dataset. Doesn't matter if it's aggregation, creation of the new column, filtering etc.

**Comment by cnuernber** [comment]
Here is one simple motivating example:

We have a dataset of stocks by month, and we want to aggregate by stocks-by-year with the price being the mean.  I implemented a columnwise reduce and then I want to compare that to using the library without the reduce.  Since the result of a reduction can be represented by a map, there are I believe two clear pathways to achieving this and I am not sure which one is better.

```clojure

user> (def stocks (ds/->dataset "test/data/stocks.csv" {:key-fn keyword}))
#'user/stocks
user> (ds/head stocks)
_unnamed [5 3]:

| :symbol |      :date | :price |
|---------+------------+--------|
|    MSFT | 2000-01-01 |  39.81 |
|    MSFT | 2000-02-01 |  36.35 |
|    MSFT | 2000-03-01 |  43.22 |
|    MSFT | 2000-04-01 |  28.37 |
|    MSFT | 2000-05-01 |  25.45 |
user> (require '[tech.v2.datatype.datetime.operations :as dtype-dt-ops])
nil
user> (def with-years (ds/add-or-update-column stocks :year (dtype-dt-ops/get-years
                                                             (stocks :date))))
#'user/with-years
user> (ds/head with-years)
_unnamed [5 4]:

| :symbol |      :date | :price | :year |
|---------+------------+--------+-------|
|    MSFT | 2000-01-01 |  39.81 |  2000 |
|    MSFT | 2000-02-01 |  36.35 |  2000 |
|    MSFT | 2000-03-01 |  43.22 |  2000 |
|    MSFT | 2000-04-01 |  28.37 |  2000 |
|    MSFT | 2000-05-01 |  25.45 |  2000 |
user> 
```

Now what I chose to do was s group-by, map a  columnwise reduction then apply ds/concat
```clojure

user> (->> (ds/group-by (juxt :symbol :year) with-years)
           (vals)
           (map (partial ds/columnwise-reduce 
                         {:symbol first 
                          :year first
                          :price dfn/mean}))
           (apply ds/concat)
           (ds/sort-by (juxt :symbol :year)))
           
_unnamed [51 3]:

| :symbol | :price | :year |
|---------+--------+-------|
|    AAPL |  21.75 |  2000 |
|    AAPL |  10.18 |  2001 |
|    AAPL |  9.408 |  2002 |
|    AAPL |  9.347 |  2003 |
```

This is no more efficient than just working in mapseq mode:

```clojure
user> (->> (ds/group-by (juxt :symbol :year) with-years)
           (vals)
           (map (fn [ds]
                  {:symbol (first (ds :symbol))
                   :year (first (ds :year))
                   :price (dfn/mean (ds :price))}))
           (sort-by (juxt :symbol :year))
           (ds/->>dataset))
           
_unnamed [51 3]:

| :symbol | :year | :price |
|---------+-------+--------|
|    AAPL |  2000 |  21.75 |
|    AAPL |  2001 |  10.18 |
|    AAPL |  2002 |  9.408 |
|    AAPL |  2003 |  9.347 |
|    AAPL |  2004 |  18.72 |
|    AAPL |  2005 |  48.17 |
```

This brings up what I think is an interesting isomorphism between a dataset with a single row and a map.

I think that isomorphism means that we could have a convention where aggregations produce maps instead of datasets makes sense as it allows you to use more of Clojure after the aggregation; you aren't limited to the dataset api.

**Comment by cnuernber** [comment]
@harold @genmeblog - I would be interested to know your thoughts on this type of reduction.  I think the argument is strong in Clojure to represent reductions just as a normal clojure hashmap and not as a dataset until you want to aggregate a sequence of reductions.

**Comment by harold** [comment]
The idea of a dataset reducing (column-wise) to a map is already interesting.

The motivating example makes me think of:
![doomed_1024x1024](https://user-images.githubusercontent.com/7443/80757308-2c1beb00-8af1-11ea-9e34-981315fde04a.png)

I'll let this rattle and see if I can think of another example to test the idea.

**Comment by keesterbrugge** [comment]
Hi all,

I'm having doubts about using the term "reduce" here.  It seems to be missing the iterative application of the function supplied to the reduction (first and dfn/mean). I thought a reduce (like in a fold) is more powerfull than what is described here, or am I misunderstanding? This functionality reminds me more of [dplyr's `summarise`](https://dplyr.tidyverse.org/reference/summarise.html) and of [incanter's `rollup`](https://github.com/incanter/incanter/blob/cf2ef07c14bcfd5fd18c1a5260a78d4cb73d623b/modules/incanter-core/src/incanter/core.clj#L1728)

> until you want to aggregate a sequence of reductions.

I don't think I understand the difference between the terms reductions (reducing) and aggregations (aggregating). Is maybe either of them always a scalar? 

Regarding the 2 pathways, I think the second pathway without `columnwise-reduce` is preferable, because I think the added value of that function is questionable if it doesn't offer extra performance or extra convenience afaict over mapping over a mapseq. 

I think if we're interleaving working on datasets and on mapseqs — which seems to be the case — I think it could be beneficial if dataset functions work also on mapseqs by first transforming them to datasets and that dataset functions always return datasets, because I think:
- this reduces surprise about whether you're working on dataset or mapseq
- you're able to continue to work in "dataset land" longer instead of having to switch back and forth to "clojure.core land"
- you reduce the amount of ->dataset and ->flyweight in a pipeline. 

Thx for the interesting discussion sofar.

**Comment by genmeblog** [comment]
With my simple [api](https://github.com/genmeblog/techtest/blob/master/src/techtest/api.clj) I can do this like that:

```clojure
(-> stocks
    (group-by (fn [row]
                {:symbol (:symbol row)
                 :year (dtype-dt-ops/get-years (:date row))}))
    (aggregate #(dfn/mean (% :price)))
    (order-by [:symbol :year])
    (select-rows (range 12)))
;; => _unnamed [12 3]:
;;    | :symbol | :year | :summary |
;;    |---------+-------+----------|
;;    |    AAPL |  2000 |    21.75 |
;;    |    AAPL |  2001 |    10.18 |
;;    |    AAPL |  2002 |    9.408 |
;;    |    AAPL |  2003 |    9.347 |
;;    |    AAPL |  2004 |    18.72 |
;;    |    AAPL |  2005 |    48.17 |
;;    |    AAPL |  2006 |    72.04 |
;;    |    AAPL |  2007 |    133.4 |
;;    |    AAPL |  2008 |    138.5 |
;;    |    AAPL |  2009 |    150.4 |
;;    |    AAPL |  2010 |    206.6 |
;;    |    AMZN |  2000 |    43.93 |

(-> stocks
    (group-by (juxt :symbol #(dtype-dt-ops/get-years (% :date))))
    (aggregate #(dfn/mean (% :price)))
    (order-by :$group-name)
    (select-rows (range 12)))
;; => _unnamed [12 2]:
;;    |  :$group-name | :summary |
;;    |---------------+----------|
;;    | ["AAPL" 2000] |    21.75 |
;;    | ["AAPL" 2001] |    10.18 |
;;    | ["AAPL" 2002] |    9.408 |
;;    | ["AAPL" 2003] |    9.347 |
;;    | ["AAPL" 2004] |    18.72 |
;;    | ["AAPL" 2005] |    48.17 |
;;    | ["AAPL" 2006] |    72.04 |
;;    | ["AAPL" 2007] |    133.4 |
;;    | ["AAPL" 2008] |    138.5 |
;;    | ["AAPL" 2009] |    150.4 |
;;    | ["AAPL" 2010] |    206.6 |
;;    | ["AMZN" 2000] |    43.93 |
```

**Comment by keesterbrugge** [comment]
@genmeblog That's quite nice!

I think it would be convenient to have a way of grouping, where 
- you don't have to manually construct a key-fn like in the first example
- where a name is optional and if key of string is used, that will also be the name 
- you get back only separate columns (so not like the example with `juxt`). 

E.g. a function like `create-keyfn` which allows the following.
```clj
(-> stocks
    (group-by (create-keyfn [:symbol [:year #(dtype-dt-ops/get-years (:date %))]]))
    (aggregate #(dfn/mean (% :price)))
    (order-by [:symbol :year])
    (select-rows (range 12)))
;; => _unnamed [12 3]:
;;    | :symbol | :year | :summary |
;;    |---------+-------+----------|
;;    |    AAPL |  2000 |    21.75 |
;;    |    AAPL |  2001 |    10.18 |
;;    |    AAPL |  2002 |    9.408 |
;;    |    AAPL |  2003 |    9.347 |
;;    |    AAPL |  2004 |    18.72 |
;;    |    AAPL |  2005 |    48.17 |
;;    |    AAPL |  2006 |    72.04 |
;;    |    AAPL |  2007 |    133.4 |
;;    |    AAPL |  2008 |    138.5 |
;;    |    AAPL |  2009 |    150.4 |
;;    |    AAPL |  2010 |    206.6 |
;;    |    AMZN |  2000 |    43.93 |
```
What do you think?

**Comment by genmeblog** [comment]
Good idea, I think we can infer such case and no `create-keyfn` is needed.

**Comment by cnuernber** [comment]
Also agreed that `columnwise-reduce` isn't what we are looking for in either functionality or name.  Very happy this is moving forward.

**Comment by cnuernber** [comment]
We should think of how to deal with issues like this now that the @genmeblog has done a good amount of development on his [API](https://github.com/genmeblog/techtest/blob/master/src/techtest/api.clj).  Potentially it is time to look at merging it in or making it really easy to use (like a jar that has `tech.ml.dataset` as a :provided scope or something).

**Comment by cnuernber** [comment]
Addressed by
https://github.com/scicloj/tablecloth
