### ISSUE TITLE
categorical column and list of categories

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.ml.dataset#48]
What is the meaning behind categorical column?

My understanding is that column is categorical when content is discrete. It can be inferred from the type but usually should be inferred from the content or user should mark such column as categorical. Not every String column is categorical. Also there are some int64 columns which are categorical.

What is interesting for me is to have an ability to get sequence of categories, without calling `unique` on the column. Maybe we should have an option: set-as-categorical on dataset and column name, which adds metatag with (lazy)list of categories.

**Comment by harold** [comment]
I think you've got it.

For me, categorical indicates that it has a relatively small number of discrete values (many fewer than the number of rows). This makes it suitable as training labels for a categorical model (as opposed to a regression model).

The library is fast enough that calling `unique` on the column is typically fine (`frequencies` is used here: https://github.com/techascent/tech.ml.dataset/blob/43a52c3bb497f99cee085251021767c3872d713d/src/tech/ml/dataset.clj#L252). In rare cases where it's not fast enough, you'd need extra smarts from the backing store to discern the categories in less than `O(n)` --- datatype's string tables have been used in this way in the past.

Hope that helps. Chris may have additional thoughts.

**Comment by genmeblog** [comment]
I'm fine with `unique` or `frequencies` if it's optimal.

**Comment by genmeblog** [comment]
Just to give real example, this dataset (https://stat.ethz.ch/R-manual/R-devel/library/lattice/html/barley.html) imported to tech.ml.dataset doesn't recognize `year` as categorical. It contain only 2 values: 1931 and 1932:

```clojure
(map meta (ds/columns barley))
;; => ({:name :yield, :size 120, :datatype :object}
;;     {:categorical? true, :name :variety, :size 120, :datatype :string}
;;     {:name :year, :size 120, :datatype :int64}
;;     {:categorical? true, :name :site, :size 120, :datatype :string})
```

**Comment by genmeblog** [comment]
Maybe different question: what is the benefit of having categorical column in tech.ml.dataset?

**Comment by cnuernber** [comment]
Categorical columns in tech.ml.dataset I guess don't have a ton of difference until you want to use 'tech.ml' on it.  Then it will change the default model type used for xgboost and smile.

The math behind categorical columns also isn't the same; they represent a different type of distribution I believe but you know about 100 times more than I on that subject.  For instance for categorical columns knowing the mode (as opposed to the mean) and knowing the set of all possible values is really useful whereas for a regular column that information isn't as or is different.  That is used in [descriptive-stats](https://github.com/techascent/tech.ml.dataset/blob/master/src/tech/ml/dataset.clj#L268) so that we can build extremely brief descriptions of a datasets that then actually do tell us useful things about them.

When using tech.ml, if you have a dataset with a numeric column that isn't categorical and you set it as an inference target you will get regression.  If you set it as a categorical column you will get classification.  This allows us to generally say we want to use `xgboost` or `smile` (or a basic nn architecture) and get back something that makes sense without more input.

**Comment by cnuernber** [comment]
Closing this as maybe this is enough information.  For sure categorical? true in the column's metadata changes how the downstream tools will interpret it and changes the descriptive stats pathway.  It does not mean the column stores the categories and so `tech.v2.dataset.column/unique` is still the most appropriate pathway.
