### ISSUE TITLE
Failed to find op

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.ml.dataset#58]
After calling `dfn/max` or `dfn/min` on column I'm getting following exception:

```
1. Unhandled java.lang.Exception
   Failed to find op: :min

  builtin_op_providers.clj:   30  tech.v2.datatype.builtin-op-providers/get-op
  builtin_op_providers.clj:   26  tech.v2.datatype.builtin-op-providers/get-op
```

**Comment by cnuernber** [comment]
Hmm, this error message should maybe be clearer.  I think you were looking for reduce-min.

**Comment by cnuernber** [comment]
The difference is a reduction always returns a scalar while the binary opts, when passed an iterable or a reader, return an iterable or a reader (and they take 2+ arguments).

**Comment by genmeblog** [comment]
Ok, got it. `reduce-min` works on numerical column though.

I have a case with character column. The first example: https://atrebas.github.io/post/2019-03-03-datatable-dplyr/#advanced-columns-manipulation.

I think some operations should work on wider range of types (like `log` on integers without casting should be also possible).

Hmmm... (why below works on seq but not on reader?)

```clojure
(dfn/log (dtype/->reader [1 2 3] :int32))
;; exception:
;;   Execution error (ExceptionInfo) at tech.v2.datatype.unary_op$reify__24374/__GT_unary_op (unary_op.clj:478).
;;   datatype is not float or double: :int32
(dfn/log [1 2 3])
;; => [0.0 0.6931471805599453 1.0986122886681098]
```

**Comment by cnuernber** [comment]
When I was working through the ames dataset, I got a lot of mathematical errors due to rounding as the sale price column loads as an integer column.  The datatype system isn't yet smart enough to know that log works in float or double space so the returned reader from log should be a float or double; current the datatype system returns the same reader type as the input reader.

This means that it is currently up the the user to ensure that operations that can only work well in float or double space happen completely in that space (or in object space).

In your first example, the operation attempts to happen in integer space and this would cause lots of rounding errors unless the returned reader type is float or double (which I haven't really gone though and figured out how to do).

Your second example uses persistent vectors  which can hold anything.  Their datatype is :object so mathematical operations on them use the clojure numerics stack and are free to change the type of the operand.

Maybe I should invest some time into allowing some operations in the datatype world to auto-promote their input to the appropriate type.  Would be less confusing than an error.

**Comment by cnuernber** [comment]
In my head I was thinking that in C++ you have to promote the operating manually as auto-promotion gets people into all manner of bad spaces but in this case it would have made the code work correctly.

**Comment by cnuernber** [comment]
Support for characters...Chars aren't a mathematical type.  In Java they are sort of a bastardized unsigned short but without a strong definition.  What I have done before is either promote them to strings or demote them to :int16 or :int32 values.  How important do you think support for them is, really?  It is a considerable about of work to add them to the datatype library and add another datatype that then increases the entire marshaling matrix, etc.

**Comment by cnuernber** [comment]
A concrete way to ask that is:
Would you pay an extra 5 seconds of startup time and another 500K of binary size to have characters be supported as first-class citizens?

**Comment by genmeblog** [comment]
haha, good question. I don't know yet. With characters I think I can rely on ordering and selecting first/last row. So no need to worry. Also it's not hard to build own max/min for this particular case (or for any comparable stuff).

**Comment by cnuernber** [comment]
Awesome, closing this for now :-).
