### ISSUE TITLE
shape

### ISSUE THREAD

**Issue by genmeblog** [techascent/tech.ml.dataset#71]
What about including `shape` function in `tech.ml.dataset`?

https://github.com/techascent/tech.ml.dataset/blob/master/src/tech/ml/dataset/impl/dataset.clj#L135

**Comment by cnuernber** [comment]
Sounds reasonable.

**Comment by cnuernber** [comment]
`dtype/shape` works on datasets and returns exactly how a naive translation of the dataset would look in memory which means a row-major representation as opposed to a column-major representation.

Would you expect the shape tuple to be row or column major?  Pandas,  data.table output the shape in column-major form.  This is why I didn't do this because if I change one thing then it doesn't match `tech.datatype` and if I do another thing then it doesn't match `Pandas` or `data.table`.

**Comment by cnuernber** [comment]
When I print the dataset I display the shape as a column-major representation to cause the least amount of confusion possible.

**Comment by genmeblog** [comment]
For me current implementation is perfectly ok
